#ifndef GAME_STATE_H
#define GAME_STATE_H

enum GameMode {
    GAME_MODE_INTRO = 0,
    GAME_MODE_TITLE = 1,
    GAME_MODE_OPTIONS = 2,
    GAME_MODE_FIELD = 3,
    GAME_MODE_PAUSE_MENU = 4,
    GAME_MODE_ITEM_SHOP = 5,
    GAME_MODE_WEAPON_SHOP = 6,
    GAME_MODE_ARMOR_SHOP = 7,
    GAME_MODE_ZOIDS_LAB = 8,
    GAME_MODE_BATTLE = 9,
    GAME_MODE_BATTLE_SCENE = 10,
    GAME_MODE_ZOID_FORM_CHANGE = 11,
    GAME_MODE_TOWN_MAP = 12,
    GAME_MODE_LINK_BATTLE = 13,
    GAME_MODE_LINK_TRADE = 14,
    GAME_MODE_DATABASE = 15,
    GAME_MODE_CHALLENGE_MENU = 16,
    GAME_MODE_LOAD_GAME = 17,
    GAME_MODE_CLEAR_DATA_SAVE = 18,
    GAME_MODE_CREDITS = 19,
    GAME_MODE_WAIT = -1
};

enum GameCompletionState {
    GAME_COMPLETION_FLAG_RAM = 0x02021770
};

#endif
