#ifndef PLAYER_SELECTION_H
#define PLAYER_SELECTION_H

#include "m2c_prelude.h"
#include "../game/player_state.h"
#include "window.h"

enum PlayerZoidSelectionFilter {
    ZOID_SELECTION_REJECT_WITHOUT_PILOT = 0x01,
    ZOID_SELECTION_REJECT_DESTROYED = 0x02,
    ZOID_SELECTION_REJECT_IN_TEAM = 0x04,
    ZOID_SELECTION_REJECT_TEMPORARY_PAIR = 0x08,
    ZOID_SELECTION_ALLOW_TEMPORARY_ALTERNATE_FORM = 0x10,
    ZOID_SELECTION_REJECT_SIZE_S = 0x40,
    ZOID_SELECTION_REJECT_SIZE_M = 0x80,
    ZOID_SELECTION_REJECT_SIZE_L = 0x100,
    ZOID_SELECTION_REJECT_SIZE_XL = 0x200,
    ZOID_SELECTION_REJECT_SIZE_DOUBLE_ICON = 0x400,
    ZOID_SELECTION_REJECT_PROTAGONIST = 0x800
};

enum PlayerPilotSelectionFilter {
    PILOT_SELECTION_REJECT_TEMPORARY_PAIR = 1
};

enum PlayerEquipmentSelectionFlags {
    EQUIPMENT_SELECTION_ALLOW_NON_COMMAND = 0x01,
    EQUIPMENT_SELECTION_ALLOW_COMMAND = 0x02,
    EQUIPMENT_SELECTION_MOUNT_MODE_MASK = 0x0C,
    EQUIPMENT_SELECTION_SIZE_MASK = 0x70,
    EQUIPMENT_SELECTION_REJECT_SMOKE_UNITS = 0x80
};

enum EquipmentMountConstraints {
    EQUIPMENT_MOUNT_MODE_MASK = 3,
    EQUIPMENT_MOUNT_MINIMUM_SIZE_MASK = 0x1C,
    EQUIPMENT_COMPATIBLE_MODEL_COUNT = 8,
    EQUIPMENT_COMPATIBLE_MODEL_TABLE_ROM = 0x087A1E2F,
    EQUIPMENT_SMOKE_FAMILY_ID = 0x1A
};

enum PlayerEquipmentSelectionStatus {
    EQUIPMENT_SELECTION_ACCEPTED = 0,
    EQUIPMENT_SELECTION_KIND_MISMATCH = 1,
    EQUIPMENT_SELECTION_MOUNT_MODE_MISMATCH = 2,
    EQUIPMENT_SELECTION_TOO_SMALL = 3,
    EQUIPMENT_SELECTION_MODEL_MISMATCH = 4,
    EQUIPMENT_SELECTION_SMOKE_PROHIBITED = 5
};

enum PlayerSelectionText {
    PLAYER_SELECTION_NORMAL_TEXT_PREFIX = 0x0001,
    PLAYER_SELECTION_REJECTED_TEXT_PREFIX = 0x0401,
    PLAYER_SELECTION_TEXT_BUFFER_RAM = 0x02030564,
    PLAYER_SELECTION_NUMBER_BUFFER_RAM = 0x020305E4,
    PLAYER_SELECTION_SPACE_TEXT_ROM = 0x081061C4,
    PLAYER_SELECTION_QUANTITY_SEPARATOR_ROM = 0x081061C8,
    PLAYER_SELECTION_CORE_NAME_COLUMNS = 10,
    PLAYER_SELECTION_RECOVERY_NAME_COLUMNS = 11,
    PARTY_HP_LABEL_TEXT_ROM = 0x081061A0,
    PARTY_HP_SEPARATOR_TEXT_ROM = 0x081061A4,
    PARTY_EMPTY_SLOT_TEXT_ROM = 0x081061A8
};

enum PlayerSelectionStorage {
    PLAYER_ZOID_SELECTION_SLOTS_RAM = 0x020321A4,
    PLAYER_ZOID_SELECTION_COUNT_RAM = 0x02032272,
    PLAYER_PILOT_SELECTION_SLOTS_RAM = 0x02032273,
    PLAYER_PILOT_SELECTION_COUNT_RAM = 0x020322A7,
    PLAYER_RECOVERY_SELECTION_IDS_RAM = 0x020322A8,
    PLAYER_RECOVERY_SELECTION_COUNT_RAM = 0x020322B1,
    PLAYER_EQUIPMENT_SELECTION_IDS_RAM = 0x020322B2,
    PLAYER_EQUIPMENT_SELECTION_COUNT_RAM = 0x02032379,
    PLAYER_MODEL_SELECTION_IDS_RAM = 0x0203237A,
    PLAYER_MODEL_SELECTION_COUNT_RAM = 0x02032411,
    PLAYER_CORE_SELECTION_IDS_RAM = 0x02032412,
    PLAYER_CORE_SELECTION_COUNT_RAM = 0x0203246B,
    PLAYER_FORM_SELECTION_IDS_RAM = 0x0203246C,
    PLAYER_FORM_SELECTION_COUNT_RAM = 0x02032472,
    PLAYER_ABILITY_SELECTION_KINDS_RAM = 0x02032473,
    PLAYER_ABILITY_SELECTION_VALUES_RAM = 0x0203247D,
    PLAYER_ABILITY_SELECTION_COUNT_RAM = 0x02032487,
    PLAYER_AUXILIARY_EFFECT_SELECTION_KINDS_RAM = 0x02032488,
    PLAYER_AUXILIARY_EFFECT_SELECTION_COUNT_RAM = 0x02032492,
    PLAYER_EQUIPMENT_SELECTION_STATUS_RAM = 0x02032AC8,
    PLAYER_ZOID_RECORDS_RAM = 0x020218E8,
    PLAYER_PILOT_RECORDS_RAM = 0x02027378,
    PLAYER_SELECTION_TEAM_SPRITES_RAM = 0x02032A88,
    PLAYER_SELECTION_NEW_SPRITES_RAM = 0x02032AA8
};

enum MenuQuantityInput {
    MENU_QUANTITY_KEY_LEFT = 0x20,
    MENU_QUANTITY_KEY_RIGHT = 0x10,
    MENU_QUANTITY_KEY_L = 0x200,
    MENU_QUANTITY_KEY_R = 0x100,
    MENU_QUANTITY_CHANGE_SOUND = 0x40
};

enum PlayerZoidModelGroupResources {
    PLAYER_ZOID_MODEL_GROUP_FIRST_ID = 200,
    PLAYER_ZOID_MODEL_GROUP_MODELS_PER_ROW = 6,
    PLAYER_ZOID_MODEL_GROUP_TABLE_ROM = 0x087A1F8C
};

enum PlayerSelectionSpriteFlags {
    PLAYER_SELECTION_SPRITE_HIDDEN = 0x20000,
    PLAYER_SELECTION_SPRITE_VISIBLE_MASK = 0xFFFDFFFF
};

enum PlayerSelectionSpriteResources {
    PLAYER_SELECTION_MAX_VISIBLE_ROWS = 8,
    PLAYER_SELECTION_MARKER_PALETTE = 15,
    PLAYER_SELECTION_TEAM_MARKER_FRAMES_ROM = 0x081053C4,
    PLAYER_SELECTION_TEAM_MARKER_ANIMATIONS_ROM = 0x081053D0,
    PLAYER_SELECTION_NEW_MARKER_FRAMES_ROM = 0x081053EC,
    PLAYER_SELECTION_NEW_MARKER_ANIMATIONS_ROM = 0x081053F8,
    PLAYER_SELECTION_TEAM_MARKER_TILE_OFFSET = 0x2C2,
    PLAYER_SELECTION_NEW_MARKER_TILE_OFFSET = 0x2C4,
    PLAYER_SELECTION_TEAM_MARKER_FLAGS = 0x108,
    PLAYER_SELECTION_NEW_MARKER_FLAGS = 0x00200108
};

struct PlayerSelectionSpriteFlagsView {
    s32 flags;
};

enum ZoidDevelopmentRequirement {
    ZOID_DEVELOPMENT_LAST_BASE_MODEL = 199,
    ZOID_DEVELOPMENT_LIGER_ZERO_SERIES = 200,
    ZOID_DEVELOPMENT_FURY_SERIES = 201,
    ZOID_DEVELOPMENT_NAME_COLUMNS = 13,
    ZOID_DEVELOPMENT_LIGER_ZERO_SERIES_TEXT_ROM = 0x081061CC,
    ZOID_DEVELOPMENT_FURY_SERIES_TEXT_ROM = 0x081061E8,
    ZOID_DEVELOPMENT_NO_CORE_TEXT_ROM = 0x08106200,
    ZOID_DEVELOPMENT_BLANK_LINE_TEXT_ROM = 0x08106238,
    ZOID_DEVELOPMENT_CAU_ONLY_TEXT_ROM = 0x08106254
};

struct ZoidDevelopmentRequirementView {
    u8 base_model_or_series_id;
    u8 required_core_id0;
    u8 required_core_id1;
    u8 reserved03;
    s32 development_price;
};

struct PlayerTeamZoidModelView {
    u8 reserved00[4];
    u8 model_id;
    u8 reserved05[0x6B];
};

/* These menus preserve signed HP and EP loads from the original code. */
struct ZoidRepairRecordView {
    u8 model_id;
    u8 palette_variant;
    u8 pilot_slot;
    u8 form_flags;
    u16 flags;
    u8 reserved06[0x33];
    u8 required_pilot_level;
    s16 max_hp;
    u8 reserved3C[2];
    s16 max_ep;
    u8 reserved40[0x30];
};

enum EmptyTeamSlotSizeLimit {
    EMPTY_TEAM_SLOT_ANY_SIZE = 0,
    EMPTY_TEAM_SLOT_SIZE_S_ONLY = 1,
    EMPTY_TEAM_SLOT_EXCLUDE_XL = 2
};

enum UnlockedZoidRecipeFilter {
    UNLOCKED_ZOID_RECIPES_ALL = 0,
    UNLOCKED_ZOID_RECIPES_SINGLE_MODEL = 1,
    UNLOCKED_ZOID_RECIPES_SERIES = 2
};

enum DestroyedZoidRepairPhase {
    ZOID_REPAIR_INITIALIZE = 0,
    ZOID_REPAIR_BUILD_LIST = 0x10,
    ZOID_REPAIR_SELECT_ZOID = 0x20,
    ZOID_REPAIR_CONFIRM = 0x30
};

enum WeaponStatHelpRow {
    WEAPON_HELP_POWER = 0,
    WEAPON_HELP_ACCURACY = 1,
    WEAPON_HELP_RANGE_AND_AREA = 2,
    WEAPON_HELP_EP_AND_WEIGHT = 3,
    WEAPON_HELP_CLASSIFICATION = 4,
    WEAPON_HELP_ATTRIBUTES = 5
};

enum EquipmentStatHelpResources {
    WEAPON_STAT_HELP_SCRIPTS_ROM = 0x087A26B0,
    COMMAND_COMMON_STAT_HELP_SCRIPTS_ROM = 0x087A26C8,
    COMMAND_EFFECT_STAT_HELP_SCRIPTS_ROM = 0x087A26D8,
    EQUIPMENT_STAT_HELP_CURSOR_Y_ROM = 0x087A2788
};

enum OptionalEquipmentMenuResources {
    OPTIONAL_WEAPON_POWER_LABEL_ROM = 0x08106ED4,
    OPTIONAL_WEAPON_POWER_BONUS_LIMIT_TEXT_ROM = 0x08106ED8,
    OPTIONAL_WEAPON_HIT_RATE_LABEL_ROM = 0x08106EDC,
    OPTIONAL_WEAPON_HIT_RATE_SUFFIX_ROM = 0x08106EE0,
    OPTIONAL_RANGED_WEAPON_TAG_ROM = 0x08106EE4,
    OPTIONAL_MELEE_WEAPON_TAG_ROM = 0x08106EEC,
    OPTIONAL_COMMAND_TAG_ROM = 0x08106EF4,
    OPTIONAL_EMPTY_SLOT_TAG_ROM = 0x08106EFC
};


struct EquipmentStatsCopyWords {
    s32 words[6];
};

struct DatabaseScanlineEventWords {
    s32 words[4];
};

struct DatabaseSpriteConstructorStackWords {
    s32 value;
    s32 preserved_word;
};

struct EquipmentStatTextPosition {
    u8 x;
    u8 y;
} __attribute__((packed));

struct EquipmentStatTextLayout {
    struct EquipmentStatTextPosition power_label;
    struct EquipmentStatTextPosition power_value;
    struct EquipmentStatTextPosition accuracy_label;
    struct EquipmentStatTextPosition accuracy_value;
    struct EquipmentStatTextPosition ep_cost_label;
    struct EquipmentStatTextPosition ep_cost_value;
    struct EquipmentStatTextPosition weight_label;
    struct EquipmentStatTextPosition weight_value;
    u8 reserved10[12];
} __attribute__((packed));

enum EquipmentStatTextResources {
    EQUIPMENT_STAT_TEXT_LAYOUTS_ROM = 0x087A1E7F,
    EQUIPMENT_STAT_TEXT_LAYOUT_BYTES = 28,
    EQUIPMENT_STAT_TEXT_LAYOUT_COUNT = 4
};


enum RecoveryItemMenuPhase {
    RECOVERY_MENU_INITIALIZE = 0x0,
    RECOVERY_MENU_REBUILD_ITEM_LIST = 0x10,
    RECOVERY_MENU_CREATE_ITEM_CURSOR = 0x1000,
    RECOVERY_MENU_SELECT_ITEM = 0x1010,
    RECOVERY_MENU_BUILD_ZOID_TARGET_LIST = 0x2000,
    RECOVERY_MENU_SELECT_ZOID_TARGET = 0x2010,
    RECOVERY_MENU_OPEN_WORLD_RETURN_MAP = 0x3000,
    RECOVERY_MENU_SELECT_WORLD_RETURN_DESTINATION = 0x3010
};

enum PlayerStatusMenuPhase {
    STATUS_MENU_INITIALIZE = 0x0,
    STATUS_MENU_CREATE_ZOID_ICON = 0x1000,
    STATUS_MENU_SELECT_ZOID = 0x1010,
    STATUS_MENU_SHOW_ZOID_STATS = 0x1020,
    STATUS_MENU_CREATE_PILOT_PORTRAIT = 0x2000,
    STATUS_MENU_SELECT_PILOT = 0x2010
};

#endif
