#ifndef SCROLLING_TEXT_H
#define SCROLLING_TEXT_H

enum ScrollingTextArrow {
    SCROLLING_TEXT_UP_ARROW = 0,
    SCROLLING_TEXT_DOWN_ARROW = 1,
    SCROLLING_TEXT_ARROW_FEEDBACK_ANIMATION = 1
};

enum ScrollingTextInput {
    SCROLLING_TEXT_KEY_UP = 0x40,
    SCROLLING_TEXT_KEY_DOWN = 0x80,
    SCROLLING_TEXT_INPUT_SOUND = 0x40
};

enum ScrollingTextLayout {
    SCROLLING_TEXT_BORDER_COLUMNS = 2,
    SCROLLING_TEXT_LINE_HEIGHT = 2,
    SCROLLING_TEXT_UP_ARROW_TILE = 0x3E6,
    SCROLLING_TEXT_DOWN_ARROW_TILE = 0x3E8,
    SCROLLING_TEXT_ARROW_PALETTE = 0xF
};

#endif
