#ifndef BATTLE_ANIMATION_H
#define BATTLE_ANIMATION_H

enum BattleAnimationLimits {
    BATTLE_ANIMATION_FINISH_DELAY_FRAMES = 30,
    BATTLE_ANIMATION_ENTRY_COUNT = 8,
    BATTLE_ANIMATION_RESOURCE_COUNT = 8,
    BATTLE_ANIMATION_SOUND_COUNT = 5,
    BATTLE_ANIMATION_GROUP_COUNT = 16,
    BATTLE_ANIMATION_GROUP_SPRITE_COUNT = 32
};

enum BattleAnimationControl {
    BATTLE_ANIMATION_VARIANT_MASK = 0x03,
    BATTLE_ANIMATION_ANCHOR_MASK = 0x3C,
    BATTLE_ANIMATION_SPRITE_PRIORITY_SHIFT = 6,
    BATTLE_ANIMATION_SPRITE_PRIORITY_MASK = 0xC0
};

enum BattleAnimationHardwareSpritePriority {
    BATTLE_ANIMATION_HARDWARE_SPRITE_PRIORITY_1 = 0x40,
    BATTLE_ANIMATION_HARDWARE_SPRITE_PRIORITY_3 = 0xC0
};

enum BattleAnimationAnchor {
    BATTLE_ANIMATION_ANCHOR_SCREEN = 0,
    BATTLE_ANIMATION_ANCHOR_WORLD = 4,
    BATTLE_ANIMATION_ANCHOR_EQUIPMENT = 8,
    BATTLE_ANIMATION_ANCHOR_ZOID_POINT_0 = 12,
    BATTLE_ANIMATION_ANCHOR_ZOID_POINT_1 = 16,
    BATTLE_ANIMATION_ANCHOR_ZOID_POINT_2 = 20,
    BATTLE_ANIMATION_ANCHOR_ZOID_POINT_3 = 24,
    BATTLE_ANIMATION_ANCHOR_ZOID_POINT_4 = 28,
    BATTLE_ANIMATION_ANCHOR_ZOID_POINT_5 = 32
};

enum BattleAnimationScriptControl {
    BATTLE_ANIMATION_SCRIPT_END = -1,
    BATTLE_ANIMATION_SCRIPT_LOOP = -2
};

enum BattleAnimationStatus {
    BATTLE_ANIMATION_IDLE = 0,
    BATTLE_ANIMATION_ACTIVE = 1,
    BATTLE_ANIMATION_SCRIPT_FINISHED = 2,
    BATTLE_ANIMATION_SKIPPED = 3
};

enum BattleAnimationResult {
    BATTLE_ANIMATION_RESULT_WAITING = 0,
    BATTLE_ANIMATION_RESULT_FINISHED = 1,
    BATTLE_ANIMATION_RESULT_SKIPPED = 2
};

enum BattleAnimationCallbackKind {
    BATTLE_ANIMATION_CALLBACK_SINGLE_SPRITE = 0,
    BATTLE_ANIMATION_CALLBACK_PROJECTILE_FLASH = 1,
    BATTLE_ANIMATION_CALLBACK_ALTERNATE_PROJECTILE_FLASH = 2,
    BATTLE_ANIMATION_CALLBACK_PROJECTILE_IMPACT_AND_EXIT = 3,
    BATTLE_ANIMATION_CALLBACK_PROJECTILE_DEBRIS = 4,
    BATTLE_ANIMATION_CALLBACK_FAST_PROJECTILE_DEBRIS = 5,
    BATTLE_ANIMATION_CALLBACK_RANDOM_HEIGHT_PROJECTILE = 6,
    BATTLE_ANIMATION_CALLBACK_SEGMENTED_BEAM = 7,
    BATTLE_ANIMATION_CALLBACK_BEAM_IMPACT_TRAIL = 8,
    BATTLE_ANIMATION_CALLBACK_BEAM_STRIP = 9,
    BATTLE_ANIMATION_CALLBACK_HELD_FRAME_PROJECTILE_FLASH = 10,
    BATTLE_ANIMATION_CALLBACK_PROJECTILE_IMPACT = 11,
    BATTLE_ANIMATION_CALLBACK_WIDE_PROJECTILE_IMPACT = 12,
    BATTLE_ANIMATION_CALLBACK_PROJECTILE_IMPACT_DEBRIS = 13,
    BATTLE_ANIMATION_CALLBACK_RANDOM_HEIGHT_HELD_FRAME_PROJECTILE = 14,
    BATTLE_ANIMATION_CALLBACK_DELAYED_PROJECTILE = 15,
    BATTLE_ANIMATION_CALLBACK_EXTENDED_DELAYED_PROJECTILE = 16,
    BATTLE_ANIMATION_CALLBACK_FOUR_SPRITE_IMPACT_TRAIL = 17,
    BATTLE_ANIMATION_CALLBACK_SIX_SPRITE_IMPACT_TRAIL = 18,
    BATTLE_ANIMATION_CALLBACK_SIX_SPRITE_IMPACT_TRAIL_DEBRIS = 19,
    BATTLE_ANIMATION_CALLBACK_SMOKE_TRAIL_PROJECTILE = 20,
    BATTLE_ANIMATION_CALLBACK_SMOKE_TRAIL_PROJECTILE_RING = 21,
    BATTLE_ANIMATION_CALLBACK_SINGLE_SMOKE_TRAIL_IMPACT = 22,
    BATTLE_ANIMATION_CALLBACK_TRIPLE_SMOKE_TRAIL_IMPACT = 23,
    BATTLE_ANIMATION_CALLBACK_FIVE_POINT_SMOKE_TRAIL_IMPACT = 24,
    BATTLE_ANIMATION_CALLBACK_RANDOM_HEIGHT_SMOKE_TRAIL_PROJECTILE = 25,
    BATTLE_ANIMATION_CALLBACK_SEGMENTED_SMOKE_TRAIL = 26,
    BATTLE_ANIMATION_CALLBACK_SMOKE_TRAIL_IMPACT_RETURN = 27,
    BATTLE_ANIMATION_CALLBACK_SMOKE_TRAIL_IMPACT_DEBRIS_RETURN = 28,
    BATTLE_ANIMATION_CALLBACK_SCREEN_WIDTH_SMOKE_TRAIL = 29,
    BATTLE_ANIMATION_CALLBACK_SOUND_AND_CAMERA_SCROLL = 30,
    BATTLE_ANIMATION_CALLBACK_FACING_SLASH = 31,
    BATTLE_ANIMATION_CALLBACK_SLASH_SPARK = 32,
    BATTLE_ANIMATION_CALLBACK_SLASH_SPARK_AND_FRAGMENT = 33,
    BATTLE_ANIMATION_CALLBACK_CHARGED_BEAM = 34,
    BATTLE_ANIMATION_CALLBACK_CHARGED_BEAM_SPARK = 35,
    BATTLE_ANIMATION_CALLBACK_CHARGED_BEAM_PARTICLE = 36,
    BATTLE_ANIMATION_CALLBACK_SCREEN_WIDTH_BEAM_IMPACT = 37,
    BATTLE_ANIMATION_CALLBACK_SCREEN_WIDTH_BEAM = 38,
    BATTLE_ANIMATION_CALLBACK_ACCELERATING_MISSILE = 39,
    BATTLE_ANIMATION_CALLBACK_MISSILE_IMPACT = 40,
    BATTLE_ANIMATION_CALLBACK_MISSILE_IMPACT_SPARK = 41,
    BATTLE_ANIMATION_CALLBACK_FOUR_POINT_MISSILE_IMPACT_SPARK = 42,
    BATTLE_ANIMATION_CALLBACK_RANDOM_HEIGHT_MISSILE = 43,
    BATTLE_ANIMATION_CALLBACK_ACCELERATING_RISING_MISSILE = 44,
    BATTLE_ANIMATION_CALLBACK_RISING_MISSILE_IMPACT = 45,
    BATTLE_ANIMATION_CALLBACK_RISING_MISSILE_IMPACT_SPARK = 46,
    BATTLE_ANIMATION_CALLBACK_FOUR_POINT_RISING_MISSILE_IMPACT_SPARK = 47,
    BATTLE_ANIMATION_CALLBACK_FALLING_MISSILE_IMPACT = 48,
    BATTLE_ANIMATION_CALLBACK_FALLING_MISSILE_IMPACT_SPARK = 49,
    BATTLE_ANIMATION_CALLBACK_FOUR_POINT_FALLING_MISSILE_IMPACT_SPARK = 50,
    BATTLE_ANIMATION_CALLBACK_RANDOM_OFFSET_RISING_MISSILE = 51,
    BATTLE_ANIMATION_CALLBACK_RANDOM_OFFSET_FALLING_MISSILE_GROUND_IMPACT = 52,
    BATTLE_ANIMATION_CALLBACK_RISING_MISSILE_FIVE_EXPLOSION_COLUMN = 53,
    BATTLE_ANIMATION_CALLBACK_RISING_MISSILE_SEVEN_EXPLOSION_COLUMN = 54,
    BATTLE_ANIMATION_CALLBACK_RISING_MISSILE_EIGHT_EXPLOSION_COLUMN = 55,
    BATTLE_ANIMATION_CALLBACK_FALLING_MISSILE_FIVE_EXPLOSION_COLUMN = 56,
    BATTLE_ANIMATION_CALLBACK_FALLING_MISSILE_SEVEN_EXPLOSION_COLUMN = 57,
    BATTLE_ANIMATION_CALLBACK_FALLING_MISSILE_EIGHT_EXPLOSION_COLUMN = 58,
    BATTLE_ANIMATION_CALLBACK_RISING_GREEN_ORB_SMOKE = 59,
    BATTLE_ANIMATION_CALLBACK_FIVE_CLOUD_RISING_GREEN_ORB_IMPACT = 60,
    BATTLE_ANIMATION_CALLBACK_TEN_CLOUD_RISING_GREEN_ORB_IMPACT = 61,
    BATTLE_ANIMATION_CALLBACK_FIVE_CLOUD_FALLING_GREEN_ORB_IMPACT = 62,
    BATTLE_ANIMATION_CALLBACK_TEN_CLOUD_FALLING_GREEN_ORB_IMPACT = 63,
    BATTLE_ANIMATION_CALLBACK_RANDOM_OFFSET_RISING_GREEN_ORB = 64,
    BATTLE_ANIMATION_CALLBACK_RANDOM_OFFSET_FALLING_GREEN_ORB_GROUND_IMPACT = 65,
    BATTLE_ANIMATION_CALLBACK_YELLOW_ORB_SMOKE = 66,
    BATTLE_ANIMATION_CALLBACK_FIVE_CLOUD_YELLOW_ORB_IMPACT = 67,
    BATTLE_ANIMATION_CALLBACK_TEN_CLOUD_YELLOW_ORB_IMPACT = 68,
    BATTLE_ANIMATION_CALLBACK_RANDOM_HEIGHT_YELLOW_ORB = 69,
    BATTLE_ANIMATION_CALLBACK_PURPLE_RING_WAVE = 70,
    BATTLE_ANIMATION_CALLBACK_PURPLE_RING_IMPACT = 71,
    BATTLE_ANIMATION_CALLBACK_SCREEN_WIDTH_PURPLE_RING = 72,
    BATTLE_ANIMATION_CALLBACK_FACING_STRIKE_PARTICLE_AND_FRAGMENT = 73,
    BATTLE_ANIMATION_CALLBACK_FACING_STRIKE_PARTICLE_AND_DELAYED_FRAGMENT = 74,
    BATTLE_ANIMATION_CALLBACK_FACING_STRIKE = 75,
    BATTLE_ANIMATION_CALLBACK_FACING_HORIZONTAL_SLASH_FRAGMENT = 76,
    BATTLE_ANIMATION_CALLBACK_FACING_HORIZONTAL_SLASH_FRAGMENT_AND_PARTICLE = 77,
    BATTLE_ANIMATION_CALLBACK_LIGHTNING_PARTICLE = 78,
    BATTLE_ANIMATION_CALLBACK_LIGHTNING_PARTICLE_AND_STREAK = 79,
    BATTLE_ANIMATION_CALLBACK_LIGHTNING_STREAK_IMPACT = 80,
    BATTLE_ANIMATION_CALLBACK_LIGHTNING_STREAK_AND_PARTICLE_IMPACT = 81,
    BATTLE_ANIMATION_CALLBACK_OFFSET_LIGHTNING = 82,
    BATTLE_ANIMATION_CALLBACK_CYAN_PAIRED_SLASH_SPARK = 83,
    BATTLE_ANIMATION_CALLBACK_CYAN_PAIRED_SLASH_SPARK_AND_FRAGMENT = 84,
    BATTLE_ANIMATION_CALLBACK_PURPLE_PAIRED_SLASH_SPARK = 85,
    BATTLE_ANIMATION_CALLBACK_PURPLE_PAIRED_SLASH_SPARK_AND_FRAGMENT = 86,
    BATTLE_ANIMATION_CALLBACK_DUST_BURST_AND_RISING_SMOKE = 87,
    BATTLE_ANIMATION_CALLBACK_CYAN_BEAM_SCROLL = 88,
    BATTLE_ANIMATION_CALLBACK_FLICKERING_SHIELD = 89,
    BATTLE_ANIMATION_CALLBACK_SINGLE_SPRITE_SOUND = 90,
    BATTLE_ANIMATION_CALLBACK_SEMITRANSPARENT_SINGLE_SPRITE_SOUND = 91,
    BATTLE_ANIMATION_CALLBACK_RED_SWEEPING_SECTOR_WINDOW = 92,
    BATTLE_ANIMATION_CALLBACK_SCANLINE_WINDOW_OPENING = 93,
    BATTLE_ANIMATION_CALLBACK_TILTED_TURQUOISE_RING_PARTICLE = 94,
    BATTLE_ANIMATION_CALLBACK_FALLING_STREAK_IMPACT_SPARK = 95,
    BATTLE_ANIMATION_CALLBACK_RANDOM_X_FALLING_STREAK = 96,
    BATTLE_ANIMATION_CALLBACK_FALLING_STREAK_GROUND_ATTACHMENT = 97,
    BATTLE_ANIMATION_CALLBACK_SCROLLING_LOOP_SPRITE = 98,
    BATTLE_ANIMATION_CALLBACK_ALTERNATING_STAR_AND_SPARK = 99,
    BATTLE_ANIMATION_CALLBACK_UNFOCUSED_SMOKE_TRAIL_PROJECTILE = 100,
    BATTLE_ANIMATION_CALLBACK_UNFOCUSED_SMOKE_TRAIL_PROJECTILE_RING = 101,
    BATTLE_ANIMATION_CALLBACK_RISING_PURPLE_SLASH_WHITE_FLASH = 102,
    BATTLE_ANIMATION_CALLBACK_LIGHTNING_FADE_AT_SORT_PRIORITY_3 = 103,
    BATTLE_ANIMATION_CALLBACK_LIGHTNING_FADE_SPARK_AND_PARTICLE = 104,
    BATTLE_ANIMATION_CALLBACK_LIGHTNING_FADE = 105,
    BATTLE_ANIMATION_CALLBACK_CHARGED_CYAN_BEAM = 106,
    BATTLE_ANIMATION_CALLBACK_CYAN_BEAM_SINE_IMPACT_TRAIL = 107,
    BATTLE_ANIMATION_CALLBACK_FIXED_X_CYAN_BEAM = 108,
    BATTLE_ANIMATION_CALLBACK_ROTATING_TRIANGLE_CHARGE_THIN_BEAM = 109,
    BATTLE_ANIMATION_CALLBACK_THIN_BEAM_BURST_IMPACT = 110,
    BATTLE_ANIMATION_CALLBACK_FIXED_X_THIN_CYAN_BEAM = 111,
    BATTLE_ANIMATION_CALLBACK_SELECTABLE_MISSILE_MOTION = 112,
    BATTLE_ANIMATION_CALLBACK_SELECTABLE_MISSILE_IMPACT = 113,
    BATTLE_ANIMATION_CALLBACK_SELECTABLE_FALLING_MISSILE_IMPACT = 114,
    BATTLE_ANIMATION_CALLBACK_RANDOM_OFFSET_SELECTABLE_RISING_MISSILE_TRAIL = 115,
    BATTLE_ANIMATION_CALLBACK_RANDOM_OFFSET_SELECTABLE_FALLING_MISSILE_GROUND_IMPACT = 116,
    BATTLE_ANIMATION_CALLBACK_THIN_BEAM_RAY_IMPACT = 117,
    BATTLE_ANIMATION_CALLBACK_SCROLLING_LOOP_YELLOW_STREAK = 118,
    BATTLE_ANIMATION_CALLBACK_CYAN_BEAM_SEQUENCE_WHITE_FLASH = 119,
    BATTLE_ANIMATION_CALLBACK_CYAN_PARTICLE_WHITE_FLASH = 120,
    BATTLE_ANIMATION_CALLBACK_ROTATING_TRIANGLE_CHARGE_PALETTE_CYCLING_BEAM = 121,
    BATTLE_ANIMATION_CALLBACK_PALETTE_CYCLING_BEAM_SINE_IMPACT_TRAIL = 122,
    BATTLE_ANIMATION_CALLBACK_FIXED_X_PALETTE_CYCLING_BEAM = 123,
    BATTLE_ANIMATION_CALLBACK_LIGHTNING_EXPLOSION_WHITE_FLASH = 124,
    BATTLE_ANIMATION_CALLBACK_RISING_MISSILE_IMPACT_FRAGMENT_FAN = 125,
    BATTLE_ANIMATION_CALLBACK_CHARGED_CYAN_ORB_PROJECTILE = 126,
    BATTLE_ANIMATION_CALLBACK_CYAN_COLUMN_WHITE_FADE_EXPLOSION_WITH_INITIAL_SHAKE = 127,
    BATTLE_ANIMATION_CALLBACK_CYAN_COLUMN_WHITE_FADE_EXPLOSION = 128,
    BATTLE_ANIMATION_CALLBACK_RANDOM_FIREBALL_BURST_WITH_INITIAL_SHAKE = 129,
    BATTLE_ANIMATION_CALLBACK_RANDOM_FIREBALL_BURST = 130,
    BATTLE_ANIMATION_CALLBACK_SMOKE_TRAIL_RING_IMPACT = 131,
    BATTLE_ANIMATION_CALLBACK_FLAME_ARC_PARTICLE_AND_RING_PROJECTILE = 132,
    BATTLE_ANIMATION_CALLBACK_FLAME_RING_SINE_IMPACT_BURST = 133,
    BATTLE_ANIMATION_CALLBACK_YELLOW_PARTICLE_BEAM_CHARGE = 134,
    BATTLE_ANIMATION_CALLBACK_YELLOW_STREAK_SINE_IMPACT_BURST = 135,
    BATTLE_ANIMATION_CALLBACK_RANDOM_HEIGHT_YELLOW_STREAK_PROJECTILE = 136
};

enum BattleAnimationPresentationKind {
    BATTLE_ANIMATION_EQUIPMENT = 0,
    BATTLE_ANIMATION_IMPACT = 1,
    BATTLE_ANIMATION_NO_IMPACT = 2,
    BATTLE_ANIMATION_STATIONARY_NO_IMPACT = 3,
    BATTLE_ANIMATION_SHIELD_IMPACT = 4,
    BATTLE_ANIMATION_SCENE = 5,
    BATTLE_ANIMATION_SLIDING_IMPACT = 6
};

enum BattleScanlineWindowMode {
    BATTLE_SCANLINE_WINDOW_DISABLED = 0,
    BATTLE_SCANLINE_WINDOW_OPENING = 1,
    BATTLE_SCANLINE_WINDOW_ACTIVE = 2,
    BATTLE_SCANLINE_WINDOW_CLOSING = 3
};

enum BattleScanlineWindowPhase {
    BATTLE_SCANLINE_WINDOW_PHASE_TRANSITION = 0,
    BATTLE_SCANLINE_WINDOW_PHASE_ACTIVE = 1,
    BATTLE_SCANLINE_WINDOW_PHASE_DISABLED = 2
};

enum BattleScanlineWindowDisplayRequest {
    BATTLE_SCANLINE_WINDOW_DISPLAY_NONE = 0,
    BATTLE_SCANLINE_WINDOW_DISPLAY_START = 1,
    BATTLE_SCANLINE_WINDOW_DISPLAY_STOP = 2
};

enum BattleBackgroundShakeState {
    BATTLE_BACKGROUND_SHAKE_IDLE = 0,
    BATTLE_BACKGROUND_SHAKE_ACTIVE = 1,
    BATTLE_BACKGROUND_SHAKE_STOPPING = 2
};

enum ZoidAnimationControl {
    ZOID_ANIMATION_SCRIPT_END = -1,
    ZOID_ANIMATION_COMPLETION_MARKER = -2,
    ZOID_ANIMATION_PLAY_SOUND = -3,
    ZOID_MOUNT_ANIMATION_FINISHED = 0x04,
    ZOID_MOUNT_ANIMATION_PAUSED = 0x08
};

struct ZoidAnimationCommand {
    s32 frame_offset_or_command;
    s32 duration_or_song;
};

struct ZoidAnimationFrameHeader {
    u16 x;
    u16 y;
    u16 width;
    u16 height;
};

struct BattleAnimationEntry {
    s16 *script;
    u8 control;
    u8 data05;
    s16 x_offset;
    u16 y_offset;
    u16 data0A;
};

struct BattleAnimationRecord {
    struct BattleAnimationEntry entries[BATTLE_ANIMATION_ENTRY_COUNT];
};

struct BattleAnimationResourceHeader {
    u16 callback_kind;
    s16 resource_ids[BATTLE_ANIMATION_RESOURCE_COUNT];
    /* Lists end with -1. The loader's eight-entry bound can cross into the next header. */
    s16 sound_ids[BATTLE_ANIMATION_SOUND_COUNT];
};

struct BattleAnimationCommand {
    s16 delay_or_command;
    u16 x;
    u16 y;
    u16 sprite_priority;
};

struct BattleAnimationState {
    u8 status;
    u8 side;
    u8 zoid_id;
    u8 equipment_slot;
    u8 resource_variant;
    u8 anchor_mode;
    s16 x_offset;
    u16 y_offset;
    u16 sprite_flags;
    u8 data0C;
    s8 presentation_kind;
    u8 spawn_count;
    u8 data0F;
    s16 *script_cursor;
    s16 *loop_start;
    u16 callback_kind;
    u16 loop_count;
    u16 delay;
    u16 data1E;
    u32 groups[BATTLE_ANIMATION_GROUP_COUNT];
};

struct BattleAnimationCallbacks {
    u32 init_callback;
    u32 update_callback;
};

enum BattleAnimationGroupFlags {
    BATTLE_ANIMATION_GROUP_ACTIVE = 1,
    BATTLE_ANIMATION_GROUP_MIRRORED = 2
};

enum BattleAnimationSpriteMirroring {
    BATTLE_ANIMATION_SPRITE_DEFAULT_FACING = 0,
    BATTLE_ANIMATION_SPRITE_REVERSE_FACING = 1,
    BATTLE_ANIMATION_SPRITE_KEEP_SCREEN_X = 2
};

enum BattleProjectileImpactPhase {
    BATTLE_PROJECTILE_IMPACT_LAUNCH = 0,
    BATTLE_PROJECTILE_IMPACT_WAIT = 1,
    BATTLE_PROJECTILE_IMPACT_FINISH = 2
};

enum BattleDelayedProjectilePhase {
    BATTLE_DELAYED_PROJECTILE_SHOW_LAUNCH_FLASH = 0,
    BATTLE_DELAYED_PROJECTILE_CREATE = 1,
    BATTLE_DELAYED_PROJECTILE_START_MOTION = 2,
    BATTLE_DELAYED_PROJECTILE_FINISH = 3
};

enum BattleProjectileTrailLimits {
    BATTLE_PROJECTILE_TRAIL_FIRST_SPRITE = 24,
    BATTLE_PROJECTILE_TRAIL_FRAMES_PER_SLOT = 4,
    BATTLE_PROJECTILE_TRAIL_EMIT_INTERVAL = 2,
    BATTLE_PROJECTILE_TRAIL_STEP_PIXELS = 16,
    BATTLE_PROJECTILE_TRAIL_SCREEN_LAST_X = 239
};

enum BattleSmokeTrailPhase {
    BATTLE_SMOKE_TRAIL_SEGMENT_COUNT = 8,
    BATTLE_SMOKE_TRAIL_START_IMPACT = 8,
    BATTLE_SMOKE_TRAIL_WAIT_IMPACT = 9,
    BATTLE_SMOKE_TRAIL_WAIT_RETURN = 10
};

enum BattleAnimationCameraMode {
    BATTLE_ANIMATION_CAMERA_IDLE = 0,
    BATTLE_ANIMATION_CAMERA_UNIT_SHAKE_AND_RECOIL_SCROLL = 5,
    BATTLE_ANIMATION_CAMERA_IMPACT_SHAKE = 6,
    BATTLE_ANIMATION_CAMERA_ACCELERATE_SCROLL = 7,
    BATTLE_ANIMATION_CAMERA_IMPACT_SHAKE_AND_RECOIL_SCROLL = 8,
    BATTLE_ANIMATION_CAMERA_EXTENDED_SCROLL_SWEEP = 10,
    BATTLE_ANIMATION_CAMERA_QUICK_SCROLL_SURGE = 11,
    BATTLE_ANIMATION_CAMERA_RECOIL_SCROLL = 12
};

enum BattleChargedBeamPhase {
    BATTLE_CHARGED_BEAM_START_CHARGE = 0,
    BATTLE_CHARGED_BEAM_EMIT_CHARGE_PARTICLES = 1,
    BATTLE_CHARGED_BEAM_WAIT_FOR_CHARGE = 2,
    BATTLE_CHARGED_BEAM_CREATE_SEGMENTS = 3,
    BATTLE_CHARGED_BEAM_WAIT_FOR_SPRITES = 4
};

enum BattleMissileImpactPhase {
    BATTLE_MISSILE_IMPACT_LAUNCH = 0,
    BATTLE_MISSILE_IMPACT_CREATE = 1,
    BATTLE_MISSILE_IMPACT_WAIT_FOR_SPRITES = 2
};

enum BattleMissileExplosionColumnPhase {
    BATTLE_MISSILE_EXPLOSION_COLUMN_LAUNCH = 0,
    BATTLE_MISSILE_EXPLOSION_COLUMN_START = 1,
    BATTLE_MISSILE_EXPLOSION_COLUMN_FIRST_BURST = 2,
    BATTLE_MISSILE_EXPLOSION_COLUMN_SECOND_BURST = 3,
    BATTLE_MISSILE_EXPLOSION_COLUMN_THIRD_BURST = 4,
    BATTLE_MISSILE_EXPLOSION_COLUMN_FOURTH_BURST = 5,
    BATTLE_MISSILE_EXPLOSION_COLUMN_FIFTH_BURST = 6,
    BATTLE_MISSILE_FIVE_EXPLOSION_COLUMN_WAIT = 4,
    BATTLE_MISSILE_SEVEN_EXPLOSION_COLUMN_WAIT = 5,
    BATTLE_MISSILE_EIGHT_EXPLOSION_COLUMN_WAIT = 7
};

enum BattleMissileExplosionColumnLimits {
    BATTLE_MISSILE_EXPLOSION_COLUMN_BURST_DELAY_FRAMES = 4
};

enum BattleProjectileTrailEffectPhase {
    BATTLE_PROJECTILE_TRAIL_CREATE = 0,
    BATTLE_PROJECTILE_TRAIL_WAIT_FOR_SPRITES = 1
};

enum BattleOrbCloudImpactPhase {
    BATTLE_ORB_CLOUD_IMPACT_LAUNCH = 0,
    BATTLE_ORB_CLOUD_IMPACT_CREATE_CLOUDS = 1,
    BATTLE_ORB_CLOUD_IMPACT_WAIT_FOR_SPRITES = 2
};

enum BattlePurpleRingLimits {
    BATTLE_PURPLE_RING_COUNT = 8,
    BATTLE_PURPLE_RING_SPACING_PIXELS = 32,
    BATTLE_PURPLE_RING_RADIAL_PARTICLE_COUNT = 16,
    BATTLE_PURPLE_RING_EXPLOSION_FIRST_SLOT = 8,
    BATTLE_PURPLE_RING_FRAGMENT_FIRST_SLOT = 16,
    BATTLE_PURPLE_RING_TRACKED_SPRITE_COUNT = 24
};

enum BattlePurpleRingImpactPhase {
    BATTLE_PURPLE_RING_IMPACT_CREATE_EXPLOSION = 8,
    BATTLE_PURPLE_RING_IMPACT_WAIT_FOR_SPRITES = 9
};

enum BattleContactEffectPhase {
    BATTLE_CONTACT_EFFECT_CREATE = 0,
    BATTLE_CONTACT_EFFECT_WAIT_FOR_SPRITES = 1
};

enum BattleDelayedStrikeFragmentPhase {
    BATTLE_DELAYED_STRIKE_FRAGMENT_CREATE = 0,
    BATTLE_DELAYED_STRIKE_FRAGMENT_WAIT_FOR_ANIMATION_STEP = 1,
    BATTLE_DELAYED_STRIKE_FRAGMENT_WAIT_FOR_SPRITES = 2
};

enum BattleLightningImpactPhase {
    BATTLE_LIGHTNING_IMPACT_CREATE = 0,
    BATTLE_LIGHTNING_IMPACT_WAIT_FOR_REPEAT_STEP = 1,
    BATTLE_LIGHTNING_IMPACT_WAIT_FOR_SPRITES = 2
};

enum BattlePairedSlashPhase {
    BATTLE_PAIRED_SLASH_CREATE = 0,
    BATTLE_PAIRED_SLASH_WAIT_FOR_SPARK_STEP = 1,
    BATTLE_PAIRED_SLASH_WAIT_FOR_SPRITES = 2
};

enum BattleContactAnimationLimits {
    BATTLE_FACING_STRIKE_FRAGMENT_ANIMATION_STEP = 6,
    BATTLE_LIGHTNING_IMPACT_REPEAT_ANIMATION_STEP = 3,
    BATTLE_PAIRED_SLASH_SPARK_ANIMATION_STEP = 5,
    BATTLE_LIGHTNING_SPRITE_HALF_WIDTH_PIXELS = 128
};

enum BattleDustBurstPhase {
    BATTLE_DUST_BURST_CREATE = 0,
    BATTLE_DUST_BURST_EMIT_RISING_SMOKE = 1,
    BATTLE_DUST_BURST_WAIT_FOR_SPRITES = 2
};

enum BattleCyanBeamScrollPhase {
    BATTLE_CYAN_BEAM_SCROLL_CREATE = 0,
    BATTLE_CYAN_BEAM_SCROLL_WAIT_FOR_CAMERA_STEP = 1,
    BATTLE_CYAN_BEAM_SCROLL_WAIT_FOR_SPRITES = 2
};

enum BattleShieldEffectPhase {
    BATTLE_SHIELD_EFFECT_CREATE = 0,
    BATTLE_SHIELD_EFFECT_WAIT_FOR_HELD_FRAME = 1
};

enum BattleSectorWindowPhase {
    BATTLE_SECTOR_WINDOW_EXTEND_LINE = 0,
    BATTLE_SECTOR_WINDOW_OPEN_SECTOR = 1,
    BATTLE_SECTOR_WINDOW_SWEEP_SECTOR = 2,
    BATTLE_SECTOR_WINDOW_CLOSE_SECTOR = 3,
    BATTLE_SECTOR_WINDOW_RETRACT_LINE = 4
};

enum BattleFallingStreakGroundPhase {
    BATTLE_FALLING_STREAK_GROUND_LAUNCH = 0,
    BATTLE_FALLING_STREAK_GROUND_ATTACH_TO_BACKGROUND = 1,
    BATTLE_FALLING_STREAK_GROUND_WAIT_FOR_SCREEN_EXIT = 2
};

enum BattleFallingStreakImpactPhase {
    BATTLE_FALLING_STREAK_IMPACT_LAUNCH = 0,
    BATTLE_FALLING_STREAK_IMPACT_CREATE_EXPLOSION_AND_SPARKS = 1,
    BATTLE_FALLING_STREAK_IMPACT_WAIT_FOR_SPRITES = 2
};

enum BattleDustBurstResourceSlot {
    BATTLE_DUST_BURST_RESOURCE_DUST = 0,
    BATTLE_DUST_BURST_RESOURCE_SMOKE = 1
};

enum BattleFallingStreakImpactResourceSlot {
    BATTLE_FALLING_STREAK_RESOURCE_STREAK = 0,
    BATTLE_FALLING_STREAK_RESOURCE_EXPLOSION = 2,
    BATTLE_FALLING_STREAK_RESOURCE_SPARK = 3
};

enum BattleStarAndSparkResourceSlot {
    BATTLE_STAR_AND_SPARK_RESOURCE_STAR = 0,
    BATTLE_STAR_AND_SPARK_RESOURCE_SPARK = 1
};

enum BattleSpecialAnimationLimits {
    BATTLE_CYAN_BEAM_SCROLL_CAMERA_ANIMATION_STEP = 8,
    BATTLE_FALLING_STREAK_FLIGHT_UPDATES = 16,
    BATTLE_SECTOR_WINDOW_ARC_VERTEX_COUNT = 7,
    BATTLE_SECTOR_WINDOW_VERTEX_COUNT = 8,
    BATTLE_SECTOR_WINDOW_RADIUS_PIXELS = 128,
    BATTLE_SECTOR_WINDOW_ANGLE_WIDTH = 32
};

enum BattleSectorWindowDisplay {
    BATTLE_SECTOR_WINDOW_INSIDE_LAYERS = 0x3F3F,
    BATTLE_SECTOR_WINDOW_OUTSIDE_LAYERS = 0x1F1F,
    BATTLE_SECTOR_WINDOW_BLEND_ALPHA = 0x0808,
    BATTLE_SECTOR_WINDOW_BLEND_CONTROL = 0x2044,
    BATTLE_SECTOR_WINDOW_BACKDROP_COLOR = 0x001F
};

enum BattleSlashWhiteFlashUpdate {
    BATTLE_SLASH_WHITE_FLASH_CREATE = 0,
    BATTLE_SLASH_WHITE_FLASH_BRIGHTEN_FIRST = 4,
    BATTLE_SLASH_WHITE_FLASH_BRIGHTEN_LAST = 19,
    BATTLE_SLASH_WHITE_FLASH_RESTORE_FIRST = 20,
    BATTLE_SLASH_WHITE_FLASH_RESTORE_LAST = 51
};

enum BattleWhiteFlashPaletteLimits {
    BATTLE_WHITE_FLASH_BACKGROUND_COLOR_COUNT = 64,
    BATTLE_WHITE_FLASH_SPRITE_COLOR_COUNT = 48,
    BATTLE_WHITE_FLASH_COLOR_CHANNEL_MASK = 31,
    BATTLE_WHITE_FLASH_INITIAL_BLEND_ALPHA = 0x1010
};

enum BattleLightningFadePhase {
    BATTLE_LIGHTNING_FADE_CREATE = 0,
    BATTLE_LIGHTNING_FADE_BLEND_BACKDROP = 1,
    BATTLE_LIGHTNING_FADE_START_SPRITE_FADE = 2,
    BATTLE_LIGHTNING_FADE_WAIT_FOR_FADE = 3
};

enum BattleLightningFadeLimits {
    BATTLE_LIGHTNING_FADE_HIDE_BLEND_PROGRESS = 8,
    BATTLE_LIGHTNING_FADE_END_BLEND_PROGRESS = 10,
    BATTLE_LIGHTNING_FADE_UPDATES = 32,
    BATTLE_LIGHTNING_FADE_SPARK_COUNT = 16,
    BATTLE_LIGHTNING_FADE_PARTICLE_COUNT = 8,
    BATTLE_LIGHTNING_FADE_PARTICLE_FIRST_SLOT = 9
};

enum BattleChargedCyanBeamPhase {
    BATTLE_CHARGED_CYAN_BEAM_EMIT_CHARGE_PARTICLES = 0,
    BATTLE_CHARGED_CYAN_BEAM_CREATE_CHARGE_ORB = 1,
    BATTLE_CHARGED_CYAN_BEAM_WAIT_FOR_CHARGE_ORB = 2,
    BATTLE_CHARGED_CYAN_BEAM_WAIT_FOR_BEAM_DELAY = 3,
    BATTLE_CHARGED_CYAN_BEAM_CREATE_BEAM = 4,
    BATTLE_CHARGED_CYAN_BEAM_WAIT_FOR_BEAM = 5
};

enum BattleCyanBeamEffectLimits {
    BATTLE_CYAN_BEAM_FIXED_X = 128,
    BATTLE_CYAN_BEAM_CHARGE_UPDATES = 60,
    BATTLE_CYAN_BEAM_DELAY_UPDATES = 30,
    BATTLE_CYAN_BEAM_IMPACT_START_ANIMATION_STEP = 2,
    BATTLE_CYAN_BEAM_SINE_IMPACT_EMISSION_COUNT = 15,
    BATTLE_CYAN_BEAM_SINE_IMPACT_TRACKED_SPRITE_COUNT = 31,
    BATTLE_CHARGE_PARTICLE_FIRST_SLOT = 1,
    BATTLE_CHARGE_PARTICLE_RADIUS_MIN = 48,
    BATTLE_CHARGE_PARTICLE_RADIUS_RANDOM_RANGE = 21,
    BATTLE_CHARGE_PARTICLE_ANGLE_MIN = 85,
    BATTLE_CHARGE_PARTICLE_ANGLE_RANDOM_RANGE = 86
};

enum BattleTriangleChargeThinBeamPhase {
    BATTLE_TRIANGLE_CHARGE_THIN_BEAM_CONFIGURE_WINDOWS = 0,
    BATTLE_TRIANGLE_CHARGE_THIN_BEAM_ROTATE_TRIANGLES = 1,
    BATTLE_TRIANGLE_CHARGE_THIN_BEAM_START_LINE = 2,
    BATTLE_TRIANGLE_CHARGE_THIN_BEAM_RETRACT_LINE = 3,
    BATTLE_TRIANGLE_CHARGE_THIN_BEAM_WAIT_FOR_FLASH_DELAY = 4,
    BATTLE_TRIANGLE_CHARGE_THIN_BEAM_CREATE_RING_AND_BEAM = 5,
    BATTLE_TRIANGLE_CHARGE_THIN_BEAM_EMIT_PARTICLES = 6,
    BATTLE_TRIANGLE_CHARGE_THIN_BEAM_WAIT_FOR_SPRITES = 7
};

enum BattleThinBeamImpactPhase {
    BATTLE_THIN_BEAM_IMPACT_CREATE_BEAM = 0,
    BATTLE_THIN_BEAM_IMPACT_WAIT_FOR_RAY_STEP = 1,
    BATTLE_THIN_BEAM_IMPACT_WAIT_FOR_IMPACT_STEP = 2,
    BATTLE_THIN_BEAM_IMPACT_EMIT_PARTICLES_AND_WAIT = 3,
    BATTLE_THIN_BEAM_IMPACT_EMIT_BURSTS = 4,
    BATTLE_THIN_BEAM_IMPACT_WAIT_FOR_BURSTS = 5
};

enum BattleThinBeamImpactLimits {
    BATTLE_THIN_BEAM_IMPACT_RAY_ANIMATION_STEP = 4,
    BATTLE_THIN_BEAM_IMPACT_TRIGGER_ANIMATION_STEP = 5,
    BATTLE_THIN_BEAM_IMPACT_LAST_PARTICLE_ANIMATION_STEP = 21,
    BATTLE_THIN_BEAM_IMPACT_BURST_UPDATES = 16
};

enum BattleCyanBeamSequenceWhiteFlashPhase {
    BATTLE_CYAN_BEAM_SEQUENCE_CREATE_RISING_ORB = 0,
    BATTLE_CYAN_BEAM_SEQUENCE_CREATE_FLASH_AND_HORIZONTAL_BEAM = 1,
    BATTLE_CYAN_BEAM_SEQUENCE_WAIT_FOR_HORIZONTAL_BEAM = 2,
    BATTLE_CYAN_BEAM_SEQUENCE_WAIT_FOR_DIAGONAL_BEAM = 3,
    BATTLE_CYAN_BEAM_SEQUENCE_WAIT_FOR_VERTICAL_BEAM_STEP = 4,
    BATTLE_CYAN_BEAM_SEQUENCE_RESTORE_PALETTES = 5,
    BATTLE_CYAN_BEAM_SEQUENCE_WAIT_FOR_SPRITES = 6
};

enum BattleCyanBeamSequenceResources {
    BATTLE_CYAN_BEAM_SEQUENCE_DIAGONAL_BEAM_RESOURCE = 0,
    BATTLE_CYAN_BEAM_SEQUENCE_HORIZONTAL_BEAM_RESOURCE = 1,
    BATTLE_CYAN_BEAM_SEQUENCE_FLASH_RESOURCE = 2,
    BATTLE_CYAN_BEAM_SEQUENCE_ORB_RESOURCE = 3,
    BATTLE_CYAN_BEAM_SEQUENCE_VERTICAL_BEAM_RESOURCE = 4,
    BATTLE_CYAN_BEAM_SEQUENCE_RING_RESOURCE = 5
};

enum BattleCyanBeamSequenceLimits {
    BATTLE_CYAN_BEAM_SEQUENCE_DELAY_UPDATES = 30,
    BATTLE_CYAN_BEAM_SEQUENCE_FLASH_ANIMATION_STEP = 4,
    BATTLE_CYAN_BEAM_SEQUENCE_SPRITE_FILL_COLOR_COUNT = 64,
    BATTLE_WHITE_FLASH_RESTORE_UPDATES = 32,
    BATTLE_WHITE_FLASH_COLOR_CHANNEL_MAX = 31,
    BATTLE_WHITE_FLASH_WHITE_COLOR = 0x7FFF
};

enum BattleCyanParticleWhiteFlashUpdate {
    BATTLE_CYAN_PARTICLE_WHITE_FLASH_WAIT_FOR_TRANSITION = 0,
    BATTLE_CYAN_PARTICLE_WHITE_FLASH_RESTORE_FIRST = 1,
    BATTLE_CYAN_PARTICLE_WHITE_FLASH_RESTORE_LAST = 31,
    BATTLE_CYAN_PARTICLE_WHITE_FLASH_FINISH = 32
};

enum BattlePaletteCyclingTriangleChargePhase {
    BATTLE_PALETTE_CYCLING_TRIANGLE_CHARGE_CONFIGURE_WINDOWS = 0,
    BATTLE_PALETTE_CYCLING_TRIANGLE_CHARGE_ROTATE_TRIANGLES = 1,
    BATTLE_PALETTE_CYCLING_TRIANGLE_CHARGE_CLEAR_PARTICLES_AND_START_LINE = 2,
    BATTLE_PALETTE_CYCLING_TRIANGLE_CHARGE_RETRACT_LINE = 3,
    BATTLE_PALETTE_CYCLING_TRIANGLE_CHARGE_WAIT_FOR_BEAM_DELAY = 4,
    BATTLE_PALETTE_CYCLING_TRIANGLE_CHARGE_CREATE_RING_AND_BEAM = 5,
    BATTLE_PALETTE_CYCLING_TRIANGLE_CHARGE_CYCLE_BEAM_PALETTE = 6
};

enum BattlePaletteCyclingTriangleChargeFlags {
    BATTLE_PALETTE_CYCLING_TRIANGLE_CHARGE_DISABLE_PARTICLES = 1
};

enum BattleLightningExplosionWhiteFlashPhase {
    BATTLE_LIGHTNING_EXPLOSION_CREATE_FIRST_LIGHTNING = 0,
    BATTLE_LIGHTNING_EXPLOSION_CREATE_SECOND_AND_THIRD_LIGHTNING = 1,
    BATTLE_LIGHTNING_EXPLOSION_CREATE_FOURTH_LIGHTNING = 2,
    BATTLE_LIGHTNING_EXPLOSION_CREATE_FIFTH_LIGHTNING = 3,
    BATTLE_LIGHTNING_EXPLOSION_EMIT_EXPLOSIONS = 4,
    BATTLE_LIGHTNING_EXPLOSION_EMIT_SMOKE = 5,
    BATTLE_LIGHTNING_EXPLOSION_WAIT_FOR_SPRITES_AND_PALETTE = 6
};

enum BattleLightningExplosionLimits {
    BATTLE_LIGHTNING_EXPLOSION_FIRST_ANIMATION_STEP = 15,
    BATTLE_LIGHTNING_EXPLOSION_SECOND_ANIMATION_STEP = 30,
    BATTLE_LIGHTNING_EXPLOSION_LAST_EMISSION_UPDATE = 20,
    BATTLE_LIGHTNING_EXPLOSION_COUNT = 6,
    BATTLE_LIGHTNING_EXPLOSION_SMOKE_COUNT = 5,
    BATTLE_LIGHTNING_EXPLOSION_TRACKED_SPRITE_COUNT = 10
};

enum BattleChargedCyanOrbProjectilePhase {
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_CHARGE = 0,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_CREATE_FAN_AND_PROJECTILE = 1,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_EMIT_TRAIL = 2,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_WAIT_FOR_SPRITES = 3
};

enum BattleChargedCyanOrbProjectileLimits {
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_ORB_CREATE_UPDATE = 48,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_LAST_CHARGE_EMISSION_STEP = 7,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_FAN_PARTICLE_COUNT = 8,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_FORWARD_PARTICLE_COUNT = 6,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_FORWARD_FIRST_SLOT = 8,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_TRAIL_FIRST_SLOT = 14,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_HORIZONTAL_SLOT = 31,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_SPEED_PIXELS = 16,
    BATTLE_CHARGED_CYAN_ORB_PROJECTILE_TRAIL_UPDATES = 50,
    BATTLE_RISING_MISSILE_IMPACT_FRAGMENT_FAN_COUNT = 5
};

union BattleTriangleChargeParameters {
    struct {
        s32 rotation_angle;
        s32 yaw_angle;
        u32 narrowing_progress;
    } window;
    struct {
        s32 length_pixels;
    } line;
    struct {
        s32 elapsed_updates;
        s32 saved_scroll_x_fixed8;
        s32 saved_scroll_y_fixed8;
    } beam;
};

struct BattleWhiteFlashPaletteBuffers {
    u16 original_background_colors[BATTLE_WHITE_FLASH_BACKGROUND_COLOR_COUNT];
    u16 blended_background_colors[BATTLE_WHITE_FLASH_BACKGROUND_COLOR_COUNT];
    u16 original_sprite_colors[BATTLE_WHITE_FLASH_SPRITE_COLOR_COUNT];
    u16 blended_sprite_colors[BATTLE_WHITE_FLASH_SPRITE_COLOR_COUNT];
};

#define BATTLE_WHITE_FLASH_PALETTE_ADDRESS(field) \
    ((u32)&((struct BattleWhiteFlashPaletteBuffers *)0x02034934)->field)

enum BattleCyanColumnWhiteFadeExplosionPhase {
    BATTLE_CYAN_COLUMN_WHITE_FADE_CREATE_STREAK = 0,
    BATTLE_CYAN_COLUMN_WHITE_FADE_CREATE_COLUMNS = 1,
    BATTLE_CYAN_COLUMN_WHITE_FADE_START_COLUMN_LOOP = 2,
    BATTLE_CYAN_COLUMN_WHITE_FADE_WAIT_BEFORE_FADE = 3,
    BATTLE_CYAN_COLUMN_WHITE_FADE_INCREASE_BRIGHTNESS = 4,
    BATTLE_CYAN_COLUMN_WHITE_FADE_EMIT_EXPLOSIONS = 5
};

enum BattleCyanColumnWhiteFadeExplosionLimits {
    BATTLE_CYAN_COLUMN_WHITE_FADE_DELAY_UPDATES = 60,
    BATTLE_CYAN_COLUMN_WHITE_FADE_BRIGHTNESS_UPDATES = 64,
    BATTLE_CYAN_COLUMN_WHITE_FADE_EXPLOSION_UPDATES = 60
};

enum BattleRandomFireballBurstPhase {
    BATTLE_RANDOM_FIREBALL_BURST_EMIT = 0,
    BATTLE_RANDOM_FIREBALL_BURST_WAIT_FOR_SPRITES = 1
};

enum BattleRandomFireballBurstLimits {
    BATTLE_RANDOM_FIREBALL_BURST_SPRITE_COUNT = 16
};

enum BattleFlameArcParticleRingPhase {
    BATTLE_FLAME_ARC_PARTICLE_RING_CREATE_ARC = 0,
    BATTLE_FLAME_ARC_PARTICLE_RING_EMIT_PARTICLES = 1,
    BATTLE_FLAME_ARC_PARTICLE_RING_WAIT_FOR_SPRITES = 2
};

enum BattleFlameArcParticleRingLimits {
    BATTLE_FLAME_ARC_PARTICLE_RING_LAUNCH_POSITION_COUNT = 17,
    BATTLE_FLAME_ARC_PARTICLE_RING_SPEED_PIXELS = 16
};

enum BattleSineImpactBurstProgress {
    BATTLE_SINE_IMPACT_BURST_LAUNCH = 0,
    BATTLE_SINE_IMPACT_BURST_WAIT_FOR_POSITION = 1,
    BATTLE_SINE_IMPACT_BURST_FIRST_EMISSION = 2,
    BATTLE_SINE_IMPACT_BURST_LAST_EMISSION = 7,
    BATTLE_SINE_IMPACT_BURST_WAIT_FOR_SPRITES = 8
};

enum BattleSineImpactBurstLimits {
    BATTLE_SINE_IMPACT_BURST_EMISSION_COUNT = 6,
    BATTLE_SINE_IMPACT_BURST_PARTICLES_PER_EMISSION = 4,
    BATTLE_SINE_IMPACT_BURST_SPRITES_PER_EMISSION = 5,
    BATTLE_SINE_IMPACT_BURST_FIRST_SLOT = 5,
    BATTLE_SINE_IMPACT_BURST_CLEANUP_SLOT_COUNT = 31,
    BATTLE_SINE_IMPACT_BURST_SPEED_PIXELS = 16
};

enum BattleYellowParticleBeamChargePhase {
    BATTLE_YELLOW_PARTICLE_BEAM_CHARGE_CREATE = 0,
    BATTLE_YELLOW_PARTICLE_BEAM_CHARGE_WAIT_FOR_FIRE_STEP = 1,
    BATTLE_YELLOW_PARTICLE_BEAM_CHARGE_WAIT_FOR_SPRITE = 2
};

enum BattleYellowParticleBeamChargeLimits {
    BATTLE_YELLOW_PARTICLE_BEAM_CHARGE_FIRE_ANIMATION_STEP = 26
};

enum BattleYellowStreakProjectilePhase {
    BATTLE_YELLOW_STREAK_PROJECTILE_CREATE = 0,
    BATTLE_YELLOW_STREAK_PROJECTILE_WAIT_FOR_SPRITE = 1
};

enum BattleYellowStreakProjectileLimits {
    BATTLE_YELLOW_STREAK_PROJECTILE_SPEED_PIXELS = 16
};

union BattleAnimationEffectParameters {
    struct {
        s32 phase_updates;
    } cyan_column_white_fade;
    struct {
        u32 emission_count;
    } random_fireball_burst;
    struct {
        u32 unused;
    } flame_arc_particle_ring;
    struct {
        s32 use_diagonal_motion;
        s32 launch_offset_pixels;
    } random_offset_selectable_missile;
    struct {
        u32 sequence_updates;
    } cyan_beam_sequence;
    struct {
        union BattleTriangleChargeParameters phase;
        u32 charge_particle_flags;
    } triangle_charge_palette_cycling_beam;
    struct {
        s32 impact_started;
        u32 emission_count;
    } palette_cycling_beam_sine_impact;
    struct {
        u32 palette_restore_updates;
        u32 explosion_updates;
        struct BattleDisplaySprite *lightning_sprite;
    } lightning_explosion_white_flash;
    struct {
        s32 impact_x;
        s32 impact_y;
        u32 unused;
    } rising_missile_fragment_fan;
    struct {
        union {
            u32 charge_updates;
            u32 trail_updates;
        } progress;
        s32 saved_scroll_x_fixed8;
        s32 saved_scroll_y_fixed8;
    } charged_cyan_orb_projectile;
    struct {
        s32 fade_updates;
        s32 backdrop_blend_progress;
    } lightning_fade;
    struct {
        s32 charge_updates;
        s32 beam_delay_updates;
    } charged_cyan_beam;
    struct {
        s32 impact_started;
        u32 emission_count;
    } cyan_beam_sine_impact;
    union BattleTriangleChargeParameters triangle_charge_thin_beam;
    struct {
        s32 particle_updates;
    } thin_beam_impact;
    struct {
        s32 use_rising_motion;
    } missile_motion_variant;
    struct {
        s32 x;
        s32 y;
        s32 use_diagonal_motion;
    } missile_impact_variant;
    struct {
        u32 smoke_count;
    } dust_burst;
    struct {
        u32 shape_progress;
        u32 sweep_count;
    } sector_window;
    struct {
        u32 depth_variant;
        u32 unused;
        s32 elapsed_updates;
    } falling_streak_ground;
    struct {
        s32 x;
        s32 y;
        s32 elapsed_frames;
    } impact;
    struct {
        s32 y;
    } random_height;
    struct {
        s32 started;
        s32 sprite_count;
    } beam_trail;
    struct {
        u32 progress_counter;
    } charged_beam;
    struct {
        s32 impact_started;
        s32 impact_count;
    } screen_width_beam_impact;
    struct {
        s32 x;
        s32 y;
        s32 elapsed_frames;
    } missile_impact;
    struct {
        s32 data00;
        s32 y_offset;
    } random_height_missile;
    struct {
        u32 unused;
        s32 y_offset;
    } random_height_offset;
    struct {
        u32 unused;
        u32 launch_x_offset_half;
    } random_diagonal_launch;
    struct {
        s32 burst_elapsed_frames;
        s32 impact_x;
    } missile_explosion_column;
    struct {
        s32 angle_x;
        u16 angle_y;
        u16 data06;
        s32 elapsed_frames;
    } rotating_triangles;
    s32 words[6];
};

struct BattleAnimationGroup {
    u32 flags;
    s32 x;
    s32 y;
    u32 sprites[BATTLE_ANIMATION_GROUP_SPRITE_COUNT];
    s32 state;
    union BattleAnimationEffectParameters effect;
    u32 sprite_flags;
    u32 init_callback;
    u32 update_callback;
};

struct BattleRandomFireballBurstGroupView {
    u32 flags;
    s32 x;
    s32 y;
    void *sprite_slots[BATTLE_ANIMATION_GROUP_SPRITE_COUNT];
    s32 phase;
    u32 emission_count;
};

#define BATTLE_ANIMATION_FIELD(group, type, field) \
    M2C_FIELD(group, type *, (s32)&((struct BattleAnimationGroup *)0)->field)

#define BATTLE_ANIMATION_OFFSET(field) \
    ((s32)&((struct BattleAnimationGroup *)0)->field)

#endif
