#ifndef DECK_COMMANDS_H
#define DECK_COMMANDS_H

#include "../../game/player_state.h"
#include "../turn_order/battle_turn_order.h"

enum DeckCommandId {
    DECK_COMMAND_NONE = 0,
    DECK_COMMAND_FRIENDSHIP = 1,
    DECK_COMMAND_CONSERVATION = 2,
    DECK_COMMAND_CHARGE_ENERGY = 3,
    DECK_COMMAND_KINGS_WAY = 4,
    DECK_COMMAND_THE_BRAVE = 5,
    DECK_COMMAND_NO_RETURN = 6,
    DECK_COMMAND_MUDDY_GROUND = 7,
    DECK_COMMAND_LOGISTICS_SUPPORT = 8,
    DECK_COMMAND_DATA_GATHER_1 = 9,
    DECK_COMMAND_DATA_GATHER_2 = 10,
    DECK_COMMAND_CORE_SECURITY_1 = 11,
    DECK_COMMAND_CORE_SECURITY_2 = 12,
    DECK_COMMAND_JUNK_PARTS = 13,
    DECK_COMMAND_SUPPLIER = 14,
    DECK_COMMAND_PROVEN_HERO = 15,
    DECK_COMMAND_MINES = 16,
    DECK_COMMAND_SANDSTORM = 17,
    DECK_COMMAND_OFF_GROUND_MINES = 18,
    DECK_COMMAND_WATER_MINES = 19,
    DECK_COMMAND_OBSTACLES = 20,
    DECK_COMMAND_COERCION = 21,
    DECK_COMMAND_FALSE_NEGO = 22,
    DECK_COMMAND_BEAM_SCREEN = 23,
    DECK_COMMAND_COVERING_FIRE = 24,
    DECK_COMMAND_DEFEND_OR_DIE = 25,
    DECK_COMMAND_LINK_SUPPORT = 26,
    DECK_COMMAND_STRATEGY_MEET = 27,
    DECK_COMMAND_DISTURBED_DATA = 28,
    DECK_COMMAND_SWITCH = 29,
    DECK_COMMAND_REDISTRIBUTION = 30,
    DECK_COMMAND_PARTS_REMOVAL = 31,
    DECK_COMMAND_DECOY = 32,
    DECK_COMMAND_GODS_TERRITORY = 33,
    DECK_COMMAND_GRAVITY_STORM = 34,
    DECK_COMMAND_T_S_WARP = 35,
    DECK_COMMAND_CONFUSION = 36,
    DECK_COMMAND_FIONAS_PRAYER = 37,
    DECK_COMMAND_JUNOS_PRAYER = 38,
    DECK_COMMAND_TWO_ARM_LIZARD_GATTAI = 39,
    DECK_COMMAND_FUZOR_DRAGON_GATTAI = 40,
    DECK_COMMAND_CHIMERA_DRAGON_GATTAI = 41,
    DECK_COMMAND_GOJULOX_GATTAI = 42,
    DECK_COMMAND_GRIFFIN_GATTAI = 43,
    DECK_COMMAND_AIRRAID = 44,
    DECK_COMMAND_KILLER_DOME_GATTAI = 45,
    DECK_COMMAND_ARROW_PHALANX = 46,
    DECK_COMMAND_T_H_PHALANX = 47,
    DECK_COMMAND_CANNON_PHALANX = 48,
    DECK_COMMAND_AEGIS_PHALANX = 49,
    DECK_COMMAND_GOJULAS_GIGA_CANNON_GATTAI = 50,
    DECK_COMMAND_LORD_GALE_GATTAI = 51
};

enum DeckCommandListMode {
    DECK_COMMAND_PLAYER_LIST = 0,
    DECK_COMMAND_BATTLE_LIST = 1
};

enum DeckCommandMenuData {
    DECK_COMMAND_COUNT = 52,
    DECK_COMMAND_SELECTED_WINDOW = 3,
    DECK_COMMAND_CATALOG_WINDOW = 4,
    DECK_COMMAND_DESCRIPTION_WINDOW = 6,
    DECK_COMMAND_CATALOG_ORDER_ROM = 0x087A2820,
    DECK_COMMAND_NAME_TABLE_ROM = 0x087EF130,
    DECK_COMMAND_DESCRIPTION_TABLE_ROM = 0x087EF200,
    DECK_COMMAND_REMOVE_TEXT_ROM = 0x08107154,
    DECK_COMMAND_TEXT_BUFFER_RAM = 0x02030564,
    DECK_COMMAND_REMOVE_ROW_PREFIX = 0x101,
    DECK_COMMAND_SELECTED_ROW_PREFIX = 0x201,
    DECK_COMMAND_UNSELECTED_ROW_PREFIX = 0x001,
    DECK_COMMAND_DESCRIPTION_SOUND = 0x41,
    DECK_COMMAND_MENU_CONFIRMED = 1,
    DECK_COMMAND_MENU_CANCELLED = 2,
    DECK_COMMAND_DESCRIPTION_KEY = 8,
    DECK_COMMAND_DESCRIPTION_CLOSE_KEYS = 3
};

enum DeckCommandMenuScript {
    DECK_COMMAND_EDITOR_OPEN_SCRIPT = 0x08019997,
    DECK_COMMAND_EDITOR_SELECT_SLOT_SCRIPT = 0x080199CF,
    DECK_COMMAND_EDITOR_SELECT_COMMAND_SCRIPT = 0x08019A0A,
    DECK_COMMAND_EDITOR_CLOSE_SCRIPT = 0x08019A3F,
    DECK_COMMAND_ADD_OPEN_SCRIPT = 0x08019A8A,
    DECK_COMMAND_ADD_SELECT_SCRIPT = 0x08019A92,
    DECK_COMMAND_ADD_CLOSE_SCRIPT = 0x08019ACB,
    DECK_COMMAND_BATTLE_SELECT_OPEN_SCRIPT = 0x08019A46,
    DECK_COMMAND_BATTLE_SELECT_LIST_SCRIPT = 0x08019A4E,
    DECK_COMMAND_BATTLE_SELECT_SCRIPT = 0x08019A82,
    DECK_COMMAND_BATTLE_SELECT_CLOSE_SCRIPT = 0x08019A86,
    DECK_COMMAND_CONSERVATION_TARGET_SCRIPT = 0x08019ACF,
    DECK_COMMAND_CHARGE_ENERGY_TARGET_SCRIPT = 0x08019B0A,
    DECK_COMMAND_FALSE_NEGO_TARGET_SCRIPT = 0x08019B45,
    DECK_COMMAND_SUPPORT_TARGET_SCRIPT = 0x08019B7C,
    DECK_COMMAND_SWITCH_TARGET_SCRIPT = 0x08019BBB,
    DECK_COMMAND_PARTS_REMOVAL_TARGET_SCRIPT = 0x08019BF0,
    DECK_COMMAND_DECOY_TARGET_SCRIPT = 0x08019C2F,
    DECK_COMMAND_RESTORE_BATTLE_WINDOWS_SCRIPT = 0x080036D3,
    DECK_COMMAND_DESCRIPTION_OPEN_SCRIPT = 0x080234E0,
    DECK_COMMAND_DESCRIPTION_CLOSE_SCRIPT = 0x080234E8
};

enum DeckCommandRequirementData {
    DECK_COMMAND_VAN_PILOT_1 = 14,
    DECK_COMMAND_VAN_PILOT_2 = 22,
    DECK_COMMAND_FIONA_PILOT_1 = 15,
    DECK_COMMAND_FIONA_PILOT_2 = 23,
    DECK_COMMAND_JUNO_PILOT_1 = 2,
    DECK_COMMAND_JUNO_PILOT_2 = 96,
    DECK_COMMAND_JUNO_PILOT_3 = 97,
    DECK_COMMAND_CANNON_ULTRA_SAURUS = 48,
    DECK_COMMAND_CANNON_ULTE_PHALANX = 140,
    DECK_COMMAND_CANNON_GRAVITY_GUN = 86,
    DECK_COMMAND_REPLACEMENT_LEVEL_LIMIT = 200,
    DECK_COMMAND_ACTION_KIND = 1,
    DECK_COMMAND_PAYLOAD_RAM = 0x0203EBD0
};

enum DeckCommandRequirementText {
    DECK_COMMAND_REQUIRES_PILOT_TEXT = 0x08107164,
    DECK_COMMAND_REQUIRES_DESTROYED_ZOID_TEXT = 0x08107194,
    DECK_COMMAND_DESTROYED_ZOID_NOT_IN_TROOP_TEXT = 0x081071CC,
    DECK_COMMAND_REQUIRES_REAR_ZOID_TEXT = 0x081071EC,
    DECK_COMMAND_NO_REAR_ZOID_TEXT = 0x08107210,
    DECK_COMMAND_REQUIRES_STRATEGY_1_TEXT = 0x08107240,
    DECK_COMMAND_PILOT_NOT_IN_TROOP_PERIOD_TEXT = 0x0810727C,
    DECK_COMMAND_ARENA_RESTRICTION_TEXT = 0x08107290,
    DECK_COMMAND_ARENA_IN_PROGRESS_TEXT = 0x081072C8,
    DECK_COMMAND_REQUIRES_STRATEGY_3_TEXT = 0x081072E8,
    DECK_COMMAND_PILOT_NOT_IN_TROOP_TEXT = 0x08107324,
    DECK_COMMAND_REQUIRES_STRATEGY_2_TEXT = 0x08107338,
    DECK_COMMAND_REQUIRES_VAN_TEXT = 0x08107374,
    DECK_COMMAND_VAN_NOT_IN_TROOP_TEXT = 0x08107394,
    DECK_COMMAND_FIONA_RESTRICTION_TEXT = 0x081073BC,
    DECK_COMMAND_PILOT_IN_TROOP_TEXT = 0x081073E0,
    DECK_COMMAND_RULE_RESTRICTION_TEXT = 0x08107400,
    DECK_COMMAND_RULE_PROHIBITS_TEXT = 0x08107418,
    DECK_COMMAND_JUNO_RESTRICTION_TEXT = 0x08107434,
    DECK_COMMAND_FORMATION_RESTRICTION_TEXT = 0x08107458,
    DECK_COMMAND_FORMATION_INVALID_TEXT = 0x08107484,
    DECK_COMMAND_WHALE_KING_UNAVAILABLE_TEXT = 0x081074A4,
    DECK_COMMAND_WHALE_KING_NOT_RESPONDING_TEXT = 0x081074C8,
    DECK_COMMAND_FORMATION_INVALID_PERIOD_TEXT = 0x081074E0,
    DECK_COMMAND_REQUIRES_RANGED_WEAPON_TEXT = 0x08107504,
    DECK_COMMAND_RANGED_WEAPON_FORMATION_TEXT = 0x0810752C,
    DECK_COMMAND_NO_RANGED_WEAPON_TEXT = 0x08107550,
    DECK_COMMAND_REQUIRES_GRAVITY_GUN_TEXT = 0x0810756C,
    DECK_COMMAND_GRAVITY_GUN_NAME_TEXT = 0x081075A0
};

struct BattleDeckCommandActionView {
    u8 kind;
    u8 command_id;
    u8 random_or_target;
    u8 data03;
};

struct BattleDeckCommandReplacement {
    u8 selected_unit_slot;
    u8 data01[0x23];
    struct PlayerZoidRecordView incoming_zoid;
};

/* Each command uses a different view of the same per-side scratch record. */
union BattleDeckCommandPayload {
    u8 selected_unit_slot;
    u8 random_byte;
    u8 formation_unit_slots[BATTLE_SIDE_COUNT][BATTLE_ACTIVE_UNIT_COUNT];
    u8 turn_order_entry_indices[BATTLE_TURN_ORDER_ENTRY_COUNT];
    s16 mean_weapon_power;
    struct BattleDeckCommandReplacement replacement;
    u8 bytes[0x94];
};

struct BattleDeckCommandPreparationStateView {
    u8 data0000[0xA07C];
    struct BattleDeckCommandActionView actions[BATTLE_SIDE_COUNT];
    union BattleDeckCommandPayload payloads[BATTLE_SIDE_COUNT];
    u8 dataA1AC[0x170];
    u8 original_party_stored_zoid_slots[BATTLE_ACTIVE_UNIT_COUNT];
} __attribute__((packed));

struct BattleDeckCommandStateView {
    u8 data0000[0x27B4];
    u8 selected_deck_commands[PLAYER_SELECTED_DECK_COMMAND_COUNT];
} __attribute__((packed));

#define BATTLE_DECK_COMMAND_OFFSET(field) \
    ((s32)&((struct BattleDeckCommandStateView *)0)->field)

#define BATTLE_DECK_PREPARATION_OFFSET(field) \
    ((s32)&((struct BattleDeckCommandPreparationStateView *)0)->field)

#define BATTLE_DECK_PAYLOAD_OFFSET(field) \
    ((s32)&((union BattleDeckCommandPayload *)0)->field)

struct BattleDeckCommandRewardStateView {
    u8 data0000[0x27BE];
    u8 persistent_command_ids[BATTLE_SIDE_COUNT];
    u8 reward_model_choice_count;
    u8 reward_model_choices[BATTLE_ACTIVE_UNIT_COUNT];
} __attribute__((packed));

#define BATTLE_DECK_REWARD_OFFSET(field) \
    ((s32)&((struct BattleDeckCommandRewardStateView *)0)->field)

#endif
