#ifndef BATTLE_POPUP_H
#define BATTLE_POPUP_H

#include "../battle_display.h"
#include "../../ui/window.h"

enum BattlePopupKind {
    BATTLE_POPUP_NONE = 0,
    BATTLE_POPUP_DAMAGE = 1,
    BATTLE_POPUP_MISS = 2,
    BATTLE_POPUP_WAITING = 3,
    BATTLE_POPUP_DESTROYED_UNIT = 4,
    BATTLE_POPUP_FREEZE = 5,
    BATTLE_POPUP_HP_MODIFIER = 6,
    BATTLE_POPUP_MAX_HP_MODIFIER = 7,
    BATTLE_POPUP_DCP_MODIFIER = 8,
    BATTLE_POPUP_EP_MODIFIER = 9,
    BATTLE_POPUP_MAX_EP_MODIFIER = 10,
    BATTLE_POPUP_EP_REGEN_MODIFIER = 11,
    BATTLE_POPUP_SPEED_MODIFIER = 12,
    BATTLE_POPUP_MOBILITY_MODIFIER = 13,
    BATTLE_POPUP_DEFENSE_MODIFIER = 14,
    BATTLE_POPUP_ARMOR_RATE_MODIFIER = 15,
    BATTLE_POPUP_SENSOR_ACCURACY_MODIFIER = 16,
    BATTLE_POPUP_LOAD_CAPACITY_MODIFIER = 17,
    BATTLE_POPUP_INITIATIVE_MODIFIER = 18,
    BATTLE_POPUP_EVASION_SCORE_MODIFIER = 19,
    BATTLE_POPUP_ATTACK_POWER_MODIFIER = 20,
    BATTLE_POPUP_HIT_RATE_MODIFIER = 21,
    BATTLE_POPUP_EVASION_BONUS = 22,
    BATTLE_POPUP_DOUBLE_ATTACK_POWER = 23,
    BATTLE_POPUP_HALF_EVASION_RATE = 24,
    BATTLE_POPUP_HALF_ATTACK_POWER = 25,
    BATTLE_POPUP_DOUBLE_EVASION_RATE = 26,
    BATTLE_POPUP_SENSOR_ACCURACY_OVERRIDE = 27,
    BATTLE_POPUP_ENERGY_SHIELD_ON = 28,
    BATTLE_POPUP_ENERGY_SHIELD_OFF = 29,
    BATTLE_POPUP_ANTI_AIR = 30,
    BATTLE_POPUP_ORGANOID = 31,
    BATTLE_POPUP_PILOT_DOWN_ARROW = 32,
    BATTLE_POPUP_PILOT_UP_ARROW = 33,
    BATTLE_POPUP_CONFUSION = 34,
    BATTLE_POPUP_CONFUSION_END = 35,
    BATTLE_POPUP_ZOS_LEVEL = 36,
    BATTLE_POPUP_DECOY = 37,
    BATTLE_POPUP_GREEN_STREAK_EFFECT = 38,
    BATTLE_POPUP_BERSERK = 39,
    BATTLE_POPUP_WAKEUP = 40,
    BATTLE_POPUP_DISSOLVING_ORB_EFFECT = 41,
    BATTLE_POPUP_PURPLE_RING_EFFECT = 42,
    BATTLE_POPUP_ZOS_OFF = 43
};

enum BattlePopupGroupFlags {
    BATTLE_POPUP_GROUP_ACTIVE = 1
};

enum BattlePopupSpriteResource {
    BATTLE_POPUP_RESOURCE_SPARK_IMPACT = 0,
    BATTLE_POPUP_RESOURCE_EXPLOSION = 1,
    BATTLE_POPUP_RESOURCE_BLUE_PARTICLES = 2,
    BATTLE_POPUP_RESOURCE_SPARKS = 3,
    BATTLE_POPUP_RESOURCE_STREAKS = 4,
    BATTLE_POPUP_RESOURCE_DISSOLVING_ORBS = 5,
    BATTLE_POPUP_RESOURCE_PURPLE_RING = 6
};

enum BattlePopupPalette {
    BATTLE_POPUP_PALETTE_GOLD_SPARKS = 0,
    BATTLE_POPUP_PALETTE_TURQUOISE_SPARKS = 1,
    BATTLE_POPUP_PALETTE_PURPLE_SPARKS = 2,
    BATTLE_POPUP_PALETTE_GREEN_STREAKS = 3,
    BATTLE_POPUP_PALETTE_PURPLE_STREAKS = 4,
    BATTLE_POPUP_PALETTE_ORANGE_STREAKS = 5,
    BATTLE_POPUP_PALETTE_ORBS = 6,
    BATTLE_POPUP_PALETTE_PURPLE_RING = 7
};

enum BattlePopupGraphicsBank {
    BATTLE_POPUP_GRAPHICS_DAMAGE = 0,
    BATTLE_POPUP_GRAPHICS_DESTROYED_UNIT = 1,
    BATTLE_POPUP_GRAPHICS_MODIFIERS = 2,
    BATTLE_POPUP_GRAPHICS_BLUE_PARTICLES = 3
};

enum BattlePopupGlyphAnimation {
    BATTLE_POPUP_GLYPH_PLUS = 26,
    BATTLE_POPUP_GLYPH_MINUS = 27,
    BATTLE_POPUP_GLYPH_SLASH = 28,
    BATTLE_POPUP_GLYPH_UP_ARROW = 29,
    BATTLE_POPUP_GLYPH_DOWN_ARROW = 30,
    BATTLE_POPUP_GLYPH_SOLID_SQUARE = 31,
    BATTLE_POPUP_GLYPH_FIRST_DIGIT = 32,
    BATTLE_POPUP_GLYPH_DIGIT_ANIMATION_BIAS = 0xF0,
    BATTLE_POPUP_GLYPH_PERCENT = 42,
    BATTLE_POPUP_GLYPH_QUESTION_MARK = 43
};

enum BattlePopupTextRom {
    BATTLE_POPUP_TEXT_MISS_ROM = 0x0810811C,
    BATTLE_POPUP_TEXT_WAITING_ROM = 0x08108124,
    BATTLE_POPUP_TEXT_FREEZE_ROM = 0x0810812C,
    BATTLE_POPUP_TEXT_HP_ROM = 0x08108134,
    BATTLE_POPUP_TEXT_MAX_HP_ROM = 0x08108138,
    BATTLE_POPUP_TEXT_DCP_ROM = 0x08108140,
    BATTLE_POPUP_TEXT_EP_ROM = 0x08108144,
    BATTLE_POPUP_TEXT_MAX_EP_ROM = 0x08108148,
    BATTLE_POPUP_TEXT_EP_REGEN_ROM = 0x08108150,
    BATTLE_POPUP_TEXT_SPEED_ROM = 0x08108154,
    BATTLE_POPUP_TEXT_MOBILITY_ROM = 0x08108158,
    BATTLE_POPUP_TEXT_DEFENSE_ROM = 0x0810815C,
    BATTLE_POPUP_TEXT_ARMOR_RATE_ROM = 0x08108160,
    BATTLE_POPUP_TEXT_SENSOR_ACCURACY_ROM = 0x08108164,
    BATTLE_POPUP_TEXT_LOAD_CAPACITY_ROM = 0x08108168,
    BATTLE_POPUP_TEXT_INITIATIVE_ROM = 0x0810816C,
    BATTLE_POPUP_TEXT_EVASION_SCORE_ROM = 0x08108170,
    BATTLE_POPUP_TEXT_ATTACK_POWER_ROM = 0x08108174,
    BATTLE_POPUP_TEXT_HIT_RATE_ROM = 0x08108178,
    BATTLE_POPUP_TEXT_EVASION_BONUS_ROM = 0x0810817C,
    BATTLE_POPUP_TEXT_DOUBLE_ATTACK_POWER_ROM = 0x08108184,
    BATTLE_POPUP_TEXT_HALF_EVASION_RATE_ROM = 0x0810818C,
    BATTLE_POPUP_TEXT_HALF_ATTACK_POWER_ROM = 0x08108198,
    BATTLE_POPUP_TEXT_DOUBLE_EVASION_RATE_ROM = 0x081081A0,
    BATTLE_POPUP_TEXT_SENSOR_ACCURACY_OVERRIDE_ROM = 0x081081AC,
    BATTLE_POPUP_TEXT_ENERGY_SHIELD_ON_ROM = 0x081081B0,
    BATTLE_POPUP_TEXT_ENERGY_SHIELD_OFF_ROM = 0x081081BC,
    BATTLE_POPUP_TEXT_ANTI_AIR_ROM = 0x081081C8,
    BATTLE_POPUP_TEXT_ORGANOID_ROM = 0x081081D4,
    BATTLE_POPUP_TEXT_PILOT_DOWN_ARROW_ROM = 0x081081E0,
    BATTLE_POPUP_TEXT_PILOT_UP_ARROW_ROM = 0x081081E8,
    BATTLE_POPUP_TEXT_CONFUSION_ROM = 0x081081F0,
    BATTLE_POPUP_TEXT_CONFUSION_END_ROM = 0x081081F8,
    BATTLE_POPUP_TEXT_ZOS_LEVEL_ROM = 0x08108204,
    BATTLE_POPUP_TEXT_DECOY_ROM = 0x08108208,
    BATTLE_POPUP_TEXT_ZOS_OFF_ROM = 0x08108210,
    BATTLE_POPUP_TEXT_BERSERK_ROM = 0x08108218,
    BATTLE_POPUP_TEXT_WAKEUP_ROM = 0x08108220
};

enum BattlePopupLimits {
    BATTLE_POPUP_KIND_COUNT = 44,
    BATTLE_POPUP_SPRITE_COUNT = 32,
    BATTLE_POPUP_EFFECT_SPRITE_SLOT = 31,
    BATTLE_POPUP_DAMAGE_DIGITS = 4,
    BATTLE_POPUP_MAX_DISPLAY_DAMAGE = 9999,
    BATTLE_POPUP_GLYPH_SPACING_PIXELS = 6,
    BATTLE_POPUP_GLYPH_RISE_UPDATES = 8,
    BATTLE_POPUP_GLYPH_LIFETIME_UPDATES = 45,
    BATTLE_POPUP_GLYPH_STAGGER_UPDATES = 2,
    BATTLE_POPUP_DAMAGE_SHAKE_LAST_UPDATE = 8,
    BATTLE_POPUP_SECOND_EXPLOSION_UPDATE = 20,
    BATTLE_POPUP_THIRD_EXPLOSION_UPDATE = 21
};

enum BattlePopupConstants {
    BATTLE_POPUP_SPRITE_RESOURCE_TABLE_ROM = 0x087AD1D0,
    BATTLE_POPUP_GLYPH_RESOURCE_TABLE_ROM = 0x087AC9F0,
    BATTLE_POPUP_GLYPH_GRAPHICS_TABLE_ROM = 0x087AC9E8,
    BATTLE_POPUP_GLYPH_CALLBACK_THUMB = 0x080C8EF5,
    BATTLE_POPUP_GROUP_SLOTS_RAM = 0x02032F64,
    BATTLE_POPUP_TEXT_BUFFER_RAM = 0x02030564,
    BATTLE_POPUP_NUMBER_BUFFER_RAM = 0x020305E4,
    BATTLE_POPUP_SIDE_ZERO_TILE_OFFSET = 0x180,
    BATTLE_POPUP_SIDE_ZERO_PALETTE_OFFSET = 6,
    BATTLE_POPUP_STREAK_TILE_OFFSET = 0x20,
    BATTLE_POPUP_ORB_TILE_OFFSET = 0x38,
    BATTLE_POPUP_RING_TILE_OFFSET = 0x58,
    BATTLE_POPUP_GLYPH_TILE_OFFSET = 0x3B4,
    BATTLE_POPUP_GLYPH_PALETTE_BANK = 13,
    BATTLE_POPUP_GLYPH_FLAGS = 0x20048,
    BATTLE_POPUP_GLYPH_VISIBLE_MASK = 0xFFFDFFFF,
    BATTLE_POPUP_HARDWARE_PRIORITY_MASK = 0xC0,
    BATTLE_POPUP_SOUND_INCREASE = 0x57,
    BATTLE_POPUP_SOUND_STATUS = 0x58,
    BATTLE_POPUP_SOUND_DAMAGE = 0x59,
    BATTLE_POPUP_SOUND_EXPLOSION = 0x5B,
    BATTLE_POPUP_SOUND_LARGE_EXPLOSION = 0x5C
};

struct BattleUnitPopupGroupView {
    u32 flags;
    s32 x;
    s32 y;
    struct BattleDisplaySprite *sprites[BATTLE_POPUP_SPRITE_COUNT];
    u32 elapsed_updates;
    u8 reserved90[0x10];
    s32 value;
    s32 side;
    s32 unit_index;
    u32 initialize_callback;
    u32 update_callback;
};

#define BATTLE_POPUP_FIELD(popup, type, field) \
    M2C_FIELD(popup, type *, (s32)&((struct BattleUnitPopupGroupView *)0)->field)

#define BATTLE_POPUP_OFFSET(field) \
    ((s32)&((struct BattleUnitPopupGroupView *)0)->field)

#endif
